contact_links:
  - name: "Manticore Team's professional services"
    about: "Looking for a faster solution to your issues with Manticore? Manticore Team can help."
    url: "https://manticoresearch.com/services"
